const LEGACY_FIELDS = {
  description: "Description",
  faq: "FAQ",
  keyFeatures: "Key Features",
  specifications: "Specifications",
  metaTitleDescription: "Meta Title & Description",
  titleFixed: "Title",
  imageRenamed: "Image Renamed & Fixed",
  productReCheck: "Product Recheck",
  category: "Category",
  attributes: "Attributes",
  deliveryCharge: "Delivery Charge",
  warranty: "Warranty",
  warrantyClaimReasons: "Warranty Claim Reasons",
  brand: "Brand",
  price: "Price",
  internalLink: "Internal Link",
};

const humanize = (value = "") => value
  .replace(/([a-z])([A-Z])/g, "$1 $2")
  .replace(/[_-]+/g, " ")
  .replace(/\b\w/g, (letter) => letter.toUpperCase());

const nonZeroActions = (values = {}, definitions = []) => {
  const definitionMap = new Map(definitions.map((item) => [item.key, item.label]));
  return Object.entries(values)
    .filter(([, value]) => Number(value) > 0)
    .map(([key, value]) => ({ key, label: definitionMap.get(key) || humanize(key), value: Number(value) }));
};

export const getReportEntries = (data = {}) => {
  // Aggregated reports carry collision-safe entries generated by the API.
  if (Array.isArray(data.reportEntries)) {
    return data.reportEntries
      .map((entry) => ({ ...entry, actions: (entry.actions || []).filter((action) => Number(action.value) > 0) }))
      .filter((entry) => entry.actions.length);
  }

  const entries = [];
  const representedDynamicKeys = new Set();
  const template = data.reportTemplate;

  (template?.groups || []).forEach((group) => {
    (group.fields || []).forEach((field) => {
      representedDynamicKeys.add(field.key);
      const actions = nonZeroActions(data.dynamicFields?.[field.key], field.counters || []);
      if (actions.length) entries.push({
        templateName: template.name || "Report",
        groupName: group.name || "Work",
        fieldKey: field.key,
        label: field.label || humanize(field.key),
        actions,
      });
    });
  });

  // Never hide values if a field was removed from a template after submission.
  Object.entries(data.dynamicFields || {}).forEach(([fieldKey, values]) => {
    if (representedDynamicKeys.has(fieldKey)) return;
    const actions = nonZeroActions(values);
    if (actions.length) entries.push({ templateName: template?.name || "Other Work", groupName: "Other", fieldKey, label: humanize(fieldKey), actions });
  });

  Object.entries(LEGACY_FIELDS).forEach(([fieldKey, label]) => {
    const actions = nonZeroActions(data[fieldKey]);
    if (actions.length) entries.push({ templateName: "Product Management", groupName: "Product Work", fieldKey, label, actions });
  });

  (data.customFields || []).forEach((field) => {
    if (Number(field.value) > 0) entries.push({
      templateName: field.templateName || template?.name || "Other Work",
      groupName: field.groupName || "Custom Work",
      fieldKey: `custom:${String(field.name).trim().toLowerCase()}`,
      label: field.name,
      actions: [{ key: "completed", label: "Completed", value: Number(field.value) }],
    });
  });

  return entries;
};

export const groupReportEntries = (entries) => {
  const groups = [];
  entries.forEach((entry) => {
    const key = `${entry.templateName}\u0000${entry.groupName}`;
    let group = groups.find((item) => item.key === key);
    if (!group) {
      group = { key, templateName: entry.templateName, groupName: entry.groupName, entries: [] };
      groups.push(group);
    }
    group.entries.push(entry);
  });
  return groups;
};

export const aggregateReportEntries = (dataItems) => {
  const merged = new Map();
  dataItems.flatMap(getReportEntries).forEach((entry) => {
    const entryKey = `${entry.templateName}\u0000${entry.groupName}\u0000${entry.fieldKey}\u0000${entry.label}`;
    if (!merged.has(entryKey)) merged.set(entryKey, { ...entry, actions: [] });
    const target = merged.get(entryKey);
    entry.actions.forEach((action) => {
      let existing = target.actions.find((item) => item.key === action.key && item.label === action.label);
      if (!existing) { existing = { ...action, value: 0 }; target.actions.push(existing); }
      existing.value += Number(action.value) || 0;
    });
  });
  return [...merged.values()];
};
